# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          
      # Check if package-lock.json is out of sync and update if necessary
      - name: Ensure lock file is in sync
        run: |
          npm install
          git diff --exit-code package-lock.json || (git add package-lock.json && git commit -m "Sync package-lock.json with package.json")

      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      # Ensure package-lock.json is in sync before publishing
      - name: Ensure lock file is in sync
        run: |
          npm install
          git diff --exit-code package-lock.json || (git add package-lock.json && git commit -m "Sync package-lock.json with package.json" && git push)
          
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
